### ISSUE TITLE
Schriftart einbetten und in moderenen Browsern nachladen

### ISSUE THREAD

**Issue by kleingeist** [kleingeist/muster#10]
- [x] wie werden schriften im web eingebunden
- [x] welche lizenz hat die schrift
- [x] alternativen (als bild rendern und text ersetzen) evaluieren

**Comment by ranzpirat** [comment]
Zu punkt 1:

https://stackoverflow.com/questions/19750647/adding-a-new-font-family-to-twitter-bootstrap
http://www.fontsquirrel.com/tools/webfont-generator

**Comment by ranzpirat** [comment]
https://www.behance.net/gallery/15706321/Kirvy-Font-Family
"Available for free download for personal or commercial use." Sollte uns genügen?

**Comment by kleingeist** [comment]
voll cool, dass so gut klappt :) ich weiß noch wie kompliziert sowas früher war. ein hoch auf neue browserenginge :)

und wenn da steht free, dann passt das auf alle fälle. voll gut :)
