### ISSUE TITLE
Seiten ausschneiden für ein Beispielvolume

### ISSUE THREAD

**Issue by kleingeist** [kleingeist/muster#13]
- [x] Rand entfernen
- [x] Farbskala entfernen

**Comment by kleingeist** [comment]
@ranzpirat HA.II.02.001 - HA.II.02.004-005 mit mustern (siehe #14 ) ausschneiden

**Comment by ranzpirat** [comment]
Siehe Ordner "edited_scans" in folgendem ftp für bearbeitete Seiten: ftp://valhalla.gnampf.eu/ (daten in mail) 

Siehe Ordner "edited_crops" für ausgeschnittene Muster. 

Script liegt im Hauptordner bei. Koordinaten und Rechteckgröße sind als JSON dict. in der jeweiligen HA.02*.txt zu finden für weitere verwendung.
