### ISSUE TITLE
Seiteninformationsleiste

### ISSUE THREAD

**Issue by ranzpirat** [kleingeist/muster#26]
- [x] Anzeige Metainformationen der angezeigten Seite
- [x] Anzeigen der Tags #21 
- [ ] Liste aller Muster der Seite die dazugehörige Vektordatei haben.

**Comment by kleingeist** [comment]
Welche Tags sollen wir denn da Anzeigen? Die der einzelnen Muster, oder die, die wir aus den Metadaten ausgelesen haben?

**Comment by ranzpirat** [comment]
An der Seitenleiste, denke ich, die der aktuell betrachteten Seite. Alle der Muster könnte zu viele werden? Ist der Aufwand sehr groß da später noch die der Muster hinzuzufügen?

**Comment by kleingeist** [comment]
insgesamt ist da gerade das datenmodell nicht passend, da zu den seiten die farben und die typen in unterschiedlichen tabellen gespeichert werden. 
der aufwand is glaub nich so wild, war mir halt nur unsicher wie das eigentlich gedacht war.

**Comment by ranzpirat** [comment]
Siehe update an Punkt 3.
