### ISSUE TITLE
Navigationbar Login Status

### ISSUE THREAD

**Issue by kleingeist** [kleingeist/muster#37]
Abhängig von #16 
- [x] Menüpunkte mit Icons 
- [x] Ein / Ausklappbar
- [ ] Optional: Zustand der Leiste speichern

**Comment by ranzpirat** [comment]
Ich schaffe es ums verrecken nicht einen kleinen Button über/auf die ul zu legen. Ein/Ausklappen läuft aktuell via Klick auf Avatar.

Außerdem: Textlinks sind nicht zentriert, neue Icons fehlen noch, (schickt mir Yoonoh, nachher)

**Comment by ranzpirat** [comment]
SAVE STATUS INTO COOCKIES JOUW
