### ISSUE TITLE
Transfer Design to HTML

### ISSUE THREAD

**Issue by kleingeist** [kleingeist/muster#8]

**Comment by kleingeist** [comment]
ich hab nun doch mal angefangen nochmal an dem design zu schrauben und bootstrap einzuführen. ist im letzten commit mit drin.

was uns noch fehlt udn was wir vielleicht auch an yonooh abgeben könnten ist es eine farbpalette zu entwerfen. links, hover, warnfarben, popups etc.
ich hab mal hier schon n paar sachen diletantisch abgeändert http://getbootstrap.com/customize/?id=327ac5298e22e0745d82

**Comment by kleingeist** [comment]
gibt auch n haufen tools mit live vorschau wie beispielsweise das hier http://bootstrap-live-customizer.com/

aber naja das is alles auch nur wichtig wenn wir sagen wir wollen primär bootstrap elemente verwenden können uns ja auch dagegen entscheiden und doch selber mehr layout machen.

**Comment by ranzpirat** [comment]
Bis auf Fontart und Schriftdicke sieht das schon sehr nah am Entwurf aus, cool.

+1 bei Bootstrap zu bleiben, das ist für mich aktuell schon verwirrend genug. :) Sprich die Farbpalette sollte an Yoonoh abgegeben werden? Ich schreib das heute Abend mal in ne Mail. Noch hat er hier keinen Schreibzugriff/liest nicht mit, glaube ich.

Was wäre der nächste Schritt um zu unserem Milestone zu kommen, die Bildervorschau, gell? Sollte das jetzt schon versucht mit angular angegangen werden? Ich versuch mich jetzt mal grob an ein paar Angular Beispielen und gucke was passiert.
